
GET http://localhost:8080/belekas/api/cart/1/f
Accept: application/json

###

GET http://localhost:8080/belekas/api/cart
Accept: application/json
Cookie: JSESSIONID=DD3298BFA2E07922DEF92419454103CF

###

POST http://localhost:8080/belekas/api/cart
Accept: application/json
Content-Type: application/json

{}

###

POST http://localhost:8080/belekas/api/cart
Accept: application/json
Content-Type: application/json

{"id": 5, "qty": 5}

###

POST http://localhost:8080/belekas/api/cart/add
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=DD3298BFA2E07922DEF92419454103CF

{"id": 1, "qty": 2}

###

DELETE http://localhost:8080/belekas/api/cart/deleteLine/2
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=DD3298BFA2E07922DEF92419454103CF

###